### ISSUE TITLE
Non Synchronized Motion in Z-Axis 

### ISSUE THREAD

**Issue by MakesmithTech** [MakesmithAccessibleTech/MakesmithFirmware#5]
A bug: If I start at 0,0,0, working in mm, and execute, for example,
G1 F30 X200.000 Y-214.000 Z-64.000
the machine gets to Z=-64 long before it gets to X=200, Y=214. On the other hand
G1 F125 X200.000 Y-214.000 Z-64.000
(which differs only in the feedrate) works properly, arriving at the final XYZ coőrdinates simultaneously. Any ideas?

**Comment by shaughanlavine** [comment]
This was an issue in the released code. It seems to work fine in the current version. Close.

**Comment by MakesmithTech** [comment]
Thanks!
